import { adminDb } from '../../infrastructure/firebase/admin.js';
import { getMemberRole, now } from '../../infrastructure/firestore/repository.js';
import { HttpError } from '../../api/middleware/auth.js';

const assetTemplates: Array<[string, string, string, string, string, string, number, number, number]> = [
  ['Cattle Group A', 'LIV-001', 'livestock', 'Cattle', 'healthy', 'Barn A', 42, 94, 82],
  ['Cattle Group B', 'LIV-002', 'livestock', 'Cattle', 'attention', 'Barn B', 36, 77, 71],
  ['Layer House 1', 'LIV-003', 'livestock', 'Chicken', 'healthy', 'Poultry House 1', 1200, 91, 88],
  ['Broiler House 2', 'LIV-004', 'livestock', 'Chicken', 'critical', 'Poultry House 2', 860, 63, 74],
  ['Feed Mixer', 'EQP-001', 'equipment', 'Mixer', 'healthy', 'Feed Center', 1, 89, 76],
  ['Automatic Feeder 01', 'EQP-002', 'equipment', 'Feeder', 'maintenance', 'Barn A', 1, 68, 93],
  ['Tractor John 5075', 'VEH-001', 'vehicle', 'Tractor', 'healthy', 'Machinery Shed', 1, 87, 64],
  ['Pickup Logistics', 'VEH-002', 'vehicle', 'Pickup', 'attention', 'Main Yard', 1, 73, 86],
  ['Cold Storage', 'FAC-001', 'facility', 'Storage', 'healthy', 'Warehouse Zone', 1, 96, 79],
  ['Water Reservoir', 'FAC-002', 'facility', 'Water', 'healthy', 'North Field', 1, 92, 58],
  ['Pond A', 'AQU-001', 'aquaculture', 'Tilapia', 'attention', 'Aquaculture Zone', 2500, 74, 80],
  ['Corn Block 3', 'CRP-001', 'crop-block', 'Corn', 'healthy', 'East Field', 6, 88, 69]
];

export async function seedDemoData(farmId: string, uid: string) {
  const role = await getMemberRole(farmId, uid);
  if (role !== 'owner' && role !== 'manager' && role !== 'operator') {
    throw new HttpError(403, 'Insufficient role to seed demo data.');
  }

  const farmRef = adminDb.doc(`farms/${farmId}`);
  const farm = await farmRef.get();
  if (!farm.exists) throw new HttpError(404, 'Farm not found.');

  const batch = adminDb.batch();
  const assetIds: string[] = [];
  const nowDate = new Date();
  const ts = now();

  assetTemplates.forEach(([name, code, category, subtype, status, location, quantity, healthScore, utilization], index) => {
    const ref = adminDb.collection(`farms/${farmId}/assets`).doc();
    assetIds.push(ref.id);
    batch.set(ref, {
      name,
      code,
      category,
      subtype,
      status,
      location,
      quantity,
      healthScore,
      utilization,
      tag: `RFID-${String(index + 1).padStart(4, '0')}`,
      notes: 'Demo asset generated by FarmFleet.',
      lastServiceAt: new Date(nowDate.getTime() - (20 + index * 3) * 86400000),
      nextServiceAt: new Date(nowDate.getTime() + (10 + index * 4) * 86400000),
      createdAt: ts,
      updatedAt: ts
    });
  });

  const metrics = [
    { metric: 'temperature', unit: '°C', base: 27, assetIndex: 2 },
    { metric: 'humidity', unit: '%', base: 69, assetIndex: 2 },
    { metric: 'feed-level', unit: '%', base: 62, assetIndex: 5 },
    { metric: 'water-level', unit: '%', base: 78, assetIndex: 9 },
    { metric: 'ph', unit: 'pH', base: 7.1, assetIndex: 10 }
  ];

  for (let day = 13; day >= 0; day -= 1) {
    metrics.forEach((item, metricIndex) => {
      const ref = adminDb.collection(`farms/${farmId}/telemetry`).doc();
      const drift = Math.sin((14 - day + metricIndex) / 2) * (metricIndex === 4 ? 0.3 : 5);
      const value = Number((item.base + drift + ((day % 3) - 1) * 0.7).toFixed(metricIndex === 4 ? 1 : 0));
      batch.set(ref, {
        assetId: assetIds[item.assetIndex],
        assetName: assetTemplates[item.assetIndex][0],
        metric: item.metric,
        value,
        unit: item.unit,
        status: item.metric === 'temperature' && value > 31 ? 'warning' : 'normal',
        source: 'demo-sensor',
        recordedAt: new Date(nowDate.getTime() - day * 86400000),
        createdAt: ts,
        updatedAt: ts
      });
    });
  }

  const tasks: Array<[string, string, string, string, number, string, number]> = [
    ['Morning feeding round', 'feeding', 'in-progress', 'high', 0, 'Operator A', 0],
    ['Inspect poultry ventilation', 'inspection', 'todo', 'critical', 3, 'Technician B', 0],
    ['Clean water line', 'cleaning', 'todo', 'medium', 2, 'Operator C', 1],
    ['Service automatic feeder', 'maintenance', 'in-progress', 'high', 5, 'Technician A', 2],
    ['Record weekly cattle weight', 'health', 'done', 'medium', 1, 'Vet Team', -1]
  ];
  tasks.forEach(([title, type, status, priority, assetIndex, assigneeName, dueOffset]) => {
    const ref = adminDb.collection(`farms/${farmId}/tasks`).doc();
    batch.set(ref, {
      title,
      type,
      status,
      priority,
      assetId: assetIds[assetIndex],
      assetName: assetTemplates[assetIndex][0],
      assigneeName,
      dueAt: new Date(nowDate.getTime() + dueOffset * 86400000),
      notes: 'Demo operational task.',
      createdAt: ts,
      updatedAt: ts
    });
  });

  const alerts: Array<[string, string, string, number, string]> = [
    ['High poultry temperature', 'critical', 'open', 3, 'Temperature exceeded the operational threshold.'],
    ['Feed level below 30%', 'warning', 'open', 5, 'Refill recommended before the next feeding cycle.'],
    ['Pickup service interval approaching', 'warning', 'open', 7, 'Preventive maintenance is due within seven days.'],
    ['Pond pH variation', 'info', 'resolved', 10, 'pH returned to the target range after aeration.']
  ];
  alerts.forEach(([title, severity, status, assetIndex, message]) => {
    const ref = adminDb.collection(`farms/${farmId}/alerts`).doc();
    batch.set(ref, {
      title,
      severity,
      status,
      assetId: assetIds[assetIndex],
      assetName: assetTemplates[assetIndex][0],
      message,
      createdAt: ts,
      updatedAt: ts,
      ...(status === 'resolved' ? { resolvedAt: ts } : {})
    });
  });

  const maintenance: Array<[string, string, number, number, number]> = [
    ['Feeder motor inspection', 'scheduled', 5, 5, 650000],
    ['Pickup oil and filter change', 'scheduled', 7, 8, 1200000],
    ['Feed mixer belt replacement', 'completed', 4, -4, 850000],
    ['Cold storage calibration', 'scheduled', 8, 14, 450000]
  ];
  maintenance.forEach(([title, status, assetIndex, dayOffset, cost]) => {
    const ref = adminDb.collection(`farms/${farmId}/maintenance`).doc();
    batch.set(ref, {
      title,
      status,
      assetId: assetIds[assetIndex],
      assetName: assetTemplates[assetIndex][0],
      scheduledAt: new Date(nowDate.getTime() + dayOffset * 86400000),
      technician: 'FarmFleet Maintenance Team',
      cost,
      notes: 'Preventive maintenance demo record.',
      createdAt: ts,
      updatedAt: ts
    });
  });

  const activities = [
    ['Created demo fleet', 'System', 'Initial assets, telemetry, tasks, alerts and maintenance records were generated.'],
    ['Completed health inspection', 'Cattle Group A', 'No critical findings.'],
    ['Updated feeding task', 'Layer House 1', 'Morning round moved to in progress.']
  ];
  activities.forEach(([action, entity, details]) => {
    const ref = adminDb.collection(`farms/${farmId}/activities`).doc();
    batch.set(ref, {
      action,
      entity,
      details,
      actorId: uid,
      actorName: 'System',
      createdAt: ts
    });
  });

  batch.update(farmRef, {
    demoSeededAt: ts,
    updatedAt: ts
  });

  await batch.commit();
  return { seeded: true };
}
